# Generated by Django 5.1.7 on 2026-08-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("grade", models.CharField(blank=True, default="", max_length=40)),
                (
                    "avatar",
                    models.CharField(blank=True, default="sparkles", max_length=40),
                ),
                ("country", models.CharField(blank=True, default="", max_length=80)),
                (
                    "country_flag",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "school_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "curriculum",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "academic_target",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "learning_style",
                    models.CharField(blank=True, default="visual", max_length=40),
                ),
                ("interests", models.JSONField(blank=True, default=list)),
                ("goal", models.CharField(blank=True, default="", max_length=200)),
                ("is_onboarded", models.BooleanField(default=False)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Primary student for this parent account (current UI is single-student).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_primary"],
                        name="students_st_user_id_29ee48_idx",
                    )
                ],
            },
        ),
    ]
