# Generated by Django 6.0.3 on 2026-08-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='students_st_user_id_29ee48_idx',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_primary',
        ),
    ]
