# Generated by Django 5.1.7 on 2026-08-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_profile_one_to_one_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="digest_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="When true, Kindling may generate weekly parent digests.",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="family_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Where to send digests; falls back to account email when blank.",
                max_length=254,
            ),
        ),
    ]
