# Generated by Django 5.1.7 on 2026-08-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_student_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("totals", models.JSONField(blank=True, default=dict)),
                ("delivery_preferences", models.JSONField(blank=True, default=dict)),
                ("affect_history", models.JSONField(blank=True, default=list)),
                ("engagement_history", models.JSONField(blank=True, default=list)),
                ("confidence_history", models.JSONField(blank=True, default=list)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("focus_areas", models.JSONField(blank=True, default=list)),
                ("behavior", models.JSONField(blank=True, default=dict)),
                ("last_session", models.JSONField(blank=True, default=dict, null=True)),
                ("raw_snapshot", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "client_student_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=160)),
                ("topic", models.CharField(blank=True, default="", max_length=200)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("counters", models.JSONField(blank=True, default=dict)),
                ("tools", models.JSONField(blank=True, default=dict)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("avg_engagement", models.FloatField(blank=True, null=True)),
                ("avg_confidence", models.FloatField(blank=True, null=True)),
                (
                    "student_profile_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("personalization", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Misconception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("misconception_id", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=200)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("subjects", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misconceptions",
                        to="learning.learningprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="SessionTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(default=0)),
                ("occurred_at", models.DateTimeField()),
                ("subject", models.CharField(blank=True, default="", max_length=160)),
                ("topic", models.CharField(blank=True, default="", max_length=200)),
                ("student_text", models.TextField(blank=True, default="")),
                ("tutor_text", models.TextField(blank=True, default="")),
                (
                    "input_modality",
                    models.CharField(blank=True, default="text", max_length=20),
                ),
                ("response_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "correctness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correct", "Correct"),
                            ("partial", "Partial"),
                            ("incorrect", "Incorrect"),
                            ("exploring", "Exploring"),
                            ("unknown", "Unknown"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "affect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("confident", "Confident"),
                            ("neutral", "Neutral"),
                            ("hesitant", "Hesitant"),
                            ("frustrated", "Frustrated"),
                            ("disengaged", "Disengaged"),
                            ("curious", "Curious"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("engagement", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("is_hint_request", models.BooleanField(default=False)),
                ("is_question", models.BooleanField(default=False)),
                ("signals", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="learning.lessonsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "index"],
            },
        ),
        migrations.CreateModel(
            name="TopicMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=160)),
                ("topic", models.CharField(max_length=200)),
                ("topic_key", models.CharField(db_index=True, max_length=360)),
                ("score", models.FloatField(default=40.0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("incorrect", models.PositiveIntegerField(default=0)),
                ("hints", models.PositiveIntegerField(default=0)),
                (
                    "last_correctness",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mastery_entries",
                        to="learning.learningprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "topic masteries",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_event_id", models.CharField(db_index=True, max_length=64)),
                (
                    "client_student_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session.start", "Session start"),
                            ("session.end", "Session end"),
                            ("turn.exchange", "Turn exchange"),
                            ("behavior.hint_requested", "Hint requested"),
                            ("behavior.tool_toggled", "Tool toggled"),
                            ("session.topic_switched", "Topic switched"),
                            ("behavior.voice_input", "Voice input"),
                            ("profile.snapshot", "Profile snapshot"),
                        ],
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, default="kindling-web", max_length=40),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_events",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["student", "event_type", "-timestamp"],
                        name="learning_le_student_673d15_idx",
                    ),
                    models.Index(
                        fields=["session_id", "event_type"],
                        name="learning_le_session_a2a98d_idx",
                    ),
                    models.Index(
                        fields=["client_event_id"],
                        name="learning_le_client__b8dcdc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client_event_id",),
                        name="uniq_learning_client_event_id",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="learningprofile",
            index=models.Index(
                fields=["client_student_id"], name="learning_le_client__617b3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonsession",
            index=models.Index(
                fields=["student", "-started_at"], name="learning_le_student_7c581a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="misconception",
            constraint=models.UniqueConstraint(
                fields=("profile", "misconception_id"),
                name="uniq_profile_misconception",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionturn",
            index=models.Index(
                fields=["session", "index"], name="learning_se_session_ab502e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topicmastery",
            constraint=models.UniqueConstraint(
                fields=("profile", "topic_key"), name="uniq_profile_topic_key"
            ),
        ),
    ]
