# Generated by Django 6.0.3 on 2026-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('session.start', 'Session start'), ('session.end', 'Session end'), ('turn.exchange', 'Turn exchange'), ('behavior.hint_requested', 'Hint requested'), ('behavior.tool_toggled', 'Tool toggled'), ('session.topic_switched', 'Topic switched'), ('behavior.voice_input', 'Voice input'), ('profile.snapshot', 'Profile snapshot'), ('intervention.offered', 'Intervention offered'), ('intervention.entered', 'Intervention entered'), ('intervention.exited', 'Intervention exited'), ('intervention.declined', 'Intervention declined')], max_length=64),
        ),
    ]
