# Generated by Django 6.0.3 on 2026-08-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_intervention_event_types'),
        ('students', '0002_student_profile_one_to_one_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_student_id', models.CharField(blank=True, default='', max_length=120)),
                ('subject', models.CharField(blank=True, default='', max_length=160)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('topic_key', models.CharField(blank=True, db_index=True, default='', max_length=360)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('next_step', models.TextField(blank=True, default='')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('api_history', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_conversations', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('tutor', 'Tutor'), ('child', 'Child'), ('system', 'System')], max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('api_user_text', models.TextField(blank=True, default='')),
                ('api_model_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.topicconversation')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='topicconversation',
            index=models.Index(fields=['student', 'topic_key', 'status'], name='learning_to_student_89db11_idx'),
        ),
        migrations.AddIndex(
            model_name='topicconversation',
            index=models.Index(fields=['student', 'subject', 'topic', 'status'], name='learning_to_student_e5a077_idx'),
        ),
        migrations.AddIndex(
            model_name='topicconversation',
            index=models.Index(fields=['client_student_id', 'topic_key'], name='learning_to_client__2d16e5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'occurred_at'], name='learning_co_convers_766808_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_message_id'), name='uniq_conversation_client_message'),
        ),
    ]
