# Generated by Django 5.1.7 on 2026-08-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_skill_skillprerequisite_topicskilllink"),
        ("learning", "0003_topic_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_know", models.FloatField(default=0.2)),
                ("score", models.FloatField(default=20.0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("incorrect", models.PositiveIntegerField(default=0)),
                ("partial", models.PositiveIntegerField(default=0)),
                ("consecutive_correct", models.PositiveIntegerField(default=0)),
                ("consecutive_incorrect", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("locked", "Growing roots"),
                            ("ready", "Ready to spark"),
                            ("learning", "Catching fire"),
                            ("mastered", "Glowing"),
                            ("rusty", "Needs a warm-up"),
                        ],
                        db_index=True,
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("last_evidence_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_correctness",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_masteries",
                        to="learning.learningprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_masteries",
                        to="curriculum.skill",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "skill masteries",
                "indexes": [
                    models.Index(
                        fields=["profile", "state"],
                        name="learning_sk_profile_e1d782_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "skill"), name="uniq_profile_skill_mastery"
                    )
                ],
            },
        ),
    ]
