# Generated by Django 5.1.7 on 2026-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_skillmastery"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicconversation",
            name="preview_text",
            field=models.CharField(blank=True, default="", max_length=240),
        ),
        migrations.AddField(
            model_name="topicconversation",
            name="resume_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
