# Generated by Django 5.1.7 on 2026-08-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_topicconversation_preview_text_and_more"),
        ("students", "0002_student_profile_one_to_one_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_student_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=160)),
                ("topic", models.CharField(blank=True, default="", max_length=200)),
                ("image", models.ImageField(upload_to="homework/%Y/%m/")),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("byte_size", models.PositiveIntegerField(default=0)),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("analyzed", "Analyzed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_uploads",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-created_at"],
                        name="learning_ho_student_c0a920_idx",
                    )
                ],
            },
        ),
    ]
