# Generated by Django 5.1.7 on 2026-08-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_manipulative_event_type"),
        ("students", "0003_parent_digest_a5"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("headline", models.CharField(blank=True, default="", max_length=200)),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-app"),
                            ("email", "Email"),
                            ("console", "Console (dev)"),
                        ],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_digests",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-period_end"],
                        name="learning_pa_student_fe276f_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="learning_pa_status_8070c0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "period_start", "period_end"),
                        name="uniq_digest_student_period",
                    )
                ],
            },
        ),
    ]
