# Generated by Django 6.0.3 on 2026-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_affect_checkin_b3'),
    ]

    operations = [
        migrations.AddField(
            model_name='misconception',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False after successful remediation until seen again.'),
        ),
        migrations.AddField(
            model_name='misconception',
            name='last_playbook',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='misconception',
            name='last_remediated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misconception',
            name='remediation_success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='misconception',
            name='skill_slug',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('session.start', 'Session start'), ('session.end', 'Session end'), ('turn.exchange', 'Turn exchange'), ('behavior.hint_requested', 'Hint requested'), ('behavior.tool_toggled', 'Tool toggled'), ('session.topic_switched', 'Topic switched'), ('behavior.voice_input', 'Voice input'), ('profile.snapshot', 'Profile snapshot'), ('intervention.offered', 'Intervention offered'), ('intervention.entered', 'Intervention entered'), ('intervention.exited', 'Intervention exited'), ('intervention.declined', 'Intervention declined'), ('behavior.manipulative_used', 'Manipulative used'), ('struggle.signal', 'Struggle signal'), ('affect.checkin', 'Affect check-in'), ('affect.persistence', 'Persistence noted'), ('misconception.detected', 'Misconception detected'), ('misconception.remediated', 'Misconception remediated')], max_length=64),
        ),
    ]
