# Generated by Django 5.1.7 on 2026-08-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "short_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("fractions", "Fractions"),
                            ("early_algebra", "Early algebra"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=40,
                    ),
                ),
                ("standard_codes", models.JSONField(blank=True, default=list)),
                ("p_init", models.FloatField(default=0.2)),
                ("p_transit", models.FloatField(default=0.12)),
                ("p_slip", models.FloatField(default=0.08)),
                ("p_guess", models.FloatField(default=0.18)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_pilot", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["domain", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("recommended", "Recommended"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                (
                    "prerequisite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="curriculum.skill",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_links",
                        to="curriculum.skill",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("skill", "prerequisite"), name="uniq_skill_prereq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TopicSkillLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(db_index=True, max_length=160)),
                ("topic_name", models.CharField(db_index=True, max_length=200)),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Contribution of this skill to topic mastery (primary ≈ 1.0)",
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_links",
                        to="curriculum.skill",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subject_name", "topic_name"],
                        name="curriculum__subject_88f8c5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject_name", "topic_name", "skill"),
                        name="uniq_topic_skill_link",
                    )
                ],
            },
        ),
    ]
