# Generated by Django 6.0.3 on 2026-08-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_skill_skillprerequisite_topicskilllink'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkedExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=400)),
                ('problem', models.TextField(help_text='Student-facing problem statement (age-appropriate).')),
                ('steps', models.JSONField(blank=True, default=list, help_text='Ordered list of short teaching steps (strings).')),
                ('takeaway', models.TextField(blank=True, default='')),
                ('counterexample', models.TextField(blank=True, default='', help_text='Optional inline common mix-up to contrast gently.')),
                ('kind', models.CharField(choices=[('example', 'Worked example'), ('counterexample', 'Counterexample')], db_index=True, default='example', max_length=20)),
                ('subject_name', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('topic_names', models.JSONField(blank=True, default=list, help_text='Lesson topic labels this example applies to.')),
                ('grade_min', models.PositiveSmallIntegerField(default=0, help_text='Inclusive minimum grade (0 ≈ Kindergarten).')),
                ('grade_max', models.PositiveSmallIntegerField(default=12, help_text='Inclusive maximum grade.')),
                ('language_notes', models.CharField(blank=True, default='', help_text='Internal cue for tone (e.g. concrete, visual-first).', max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worked_examples', to='curriculum.skill')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['subject_name', 'is_active'], name='curriculum__subject_ca9654_idx'), models.Index(fields=['skill', 'kind', 'is_active'], name='curriculum__skill_i_2dbbec_idx')],
            },
        ),
    ]
