# Generated by Django 6.0.3 on 2026-08-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_worked_example_b4'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisconceptionDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('fractions', 'Fractions'), ('early_algebra', 'Early algebra'), ('general', 'General')], db_index=True, default='general', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('topic_names', models.JSONField(blank=True, default=list)),
                ('student_cues', models.JSONField(blank=True, default=list, help_text='Regex list matched primarily against student text.')),
                ('patterns', models.JSONField(blank=True, default=list, help_text='Regex list matched against student+tutor blob.')),
                ('playbook', models.JSONField(blank=True, default=dict, help_text='Remediation playbook: open, steps, check_question, tutor_directives, success_signal.')),
                ('related_example_slug', models.SlugField(blank=True, default='', max_length=80)),
                ('related_counter_slug', models.SlugField(blank=True, default='', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misconception_defs', to='curriculum.skill')),
            ],
            options={
                'verbose_name': 'misconception definition',
                'verbose_name_plural': 'misconception definitions',
                'ordering': ['domain', 'sort_order', 'label'],
            },
        ),
    ]
