# Generated by Django 6.0.3 on 2026-08-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_misconception_engine_b5'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStepProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('subject_name', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('topic_names', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('final_expected', models.CharField(blank=True, default='', max_length=80)),
                ('final_alts', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multistep_problems', to='curriculum.skill')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
