"""
Pilot worked-example library (Epic B4).

Age-appropriate language, linked to pilot skills, with counterexamples.
Seeded into WorkedExample rows by seed_kindling.
"""

from __future__ import annotations

from typing import Any, Dict, List

# grade_min/max are inclusive US-style grade numbers (K≈0).
WORKED_EXAMPLES: List[Dict[str, Any]] = [
    {
        "slug": "we.frac.parts_pizza",
        "skill_slug": "frac.parts_of_whole",
        "title": "Pizza halves",
        "summary": "A pizza cut into 2 equal parts — each is 1/2.",
        "problem": "A pizza is cut into 2 equal slices. What fraction is one slice?",
        "steps": [
            "The whole pizza is 1 whole.",
            "It is split into 2 equal parts, so each part is the same size.",
            "One of those equal parts is written 1/2 (one out of two).",
        ],
        "takeaway": "Equal parts of a whole → unit fraction 1/n.",
        "counterexample": "Cutting into 2 parts that are not equal is not halves.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Fraction sense", "Parts of a whole", "Equal parts"],
        "grade_min": 2,
        "grade_max": 5,
        "sort_order": 10,
    },
    {
        "slug": "we.frac.parts_chocolate",
        "skill_slug": "frac.parts_of_whole",
        "title": "Chocolate bar fourths",
        "summary": "Four equal squares make fourths.",
        "problem": "A chocolate bar is broken into 4 equal squares. What fraction is one square?",
        "steps": [
            "The whole bar is 1 whole.",
            "There are 4 equal squares.",
            "One square is 1 out of 4 equal parts → 1/4.",
        ],
        "takeaway": "The bottom number counts how many equal pieces make the whole.",
        "counterexample": "If the pieces are different sizes, we cannot name them as equal-part fractions yet.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Fraction sense"],
        "grade_min": 2,
        "grade_max": 5,
        "sort_order": 11,
    },
    {
        "slug": "we.frac.num_den_bar",
        "skill_slug": "frac.numerator_denominator",
        "title": "Reading 3/4 on a bar",
        "summary": "Numerator counts shaded parts; denominator counts equal parts.",
        "problem": "A bar is split into 4 equal pieces and 3 are shaded. What fraction is shaded?",
        "steps": [
            "Count the equal pieces in the whole bar → 4. That is the denominator.",
            "Count the shaded pieces → 3. That is the numerator.",
            "Write shaded-over-whole: 3/4.",
        ],
        "takeaway": "Numerator = how many; denominator = how many equal parts make the whole.",
        "counterexample": "Do not swap top and bottom — 4/3 would mean something different.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Fraction sense", "Numerator and denominator", "Reading fractions"],
        "grade_min": 2,
        "grade_max": 5,
        "sort_order": 20,
    },
    {
        "slug": "we.frac.num_den_swap_counter",
        "skill_slug": "frac.numerator_denominator",
        "title": "Not upside-down!",
        "summary": "Counterexample: swapping num/den changes the amount.",
        "problem": "Is 2/5 the same as 5/2?",
        "steps": [
            "2/5 means 2 equal fifths of a whole — less than 1 whole.",
            "5/2 means 5 halves — more than 2 wholes.",
            "They are not the same amount.",
        ],
        "takeaway": "Top and bottom have different jobs — do not flip them casually.",
        "counterexample": "",
        "kind": "counterexample",
        "subject_name": "Math Foundations",
        "topic_names": ["Fraction sense"],
        "grade_min": 3,
        "grade_max": 6,
        "sort_order": 21,
    },
    {
        "slug": "we.frac.number_line_three_fourths",
        "skill_slug": "frac.number_line",
        "title": "3/4 on the number line",
        "summary": "Split 0–1 into fourths; count three jumps.",
        "problem": "Where is 3/4 on a number line from 0 to 1?",
        "steps": [
            "Draw a line from 0 to 1.",
            "Split the space into 4 equal jumps (fourths).",
            "Start at 0 and take 3 jumps → that point is 3/4.",
        ],
        "takeaway": "The denominator is how many equal jumps fill 0 to 1; the numerator is how many jumps you take.",
        "counterexample": "Marking 3 tick marks without equal spacing is not a fair number line.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Fractions on a number line", "Fraction sense"],
        "grade_min": 3,
        "grade_max": 5,
        "sort_order": 30,
    },
    {
        "slug": "we.frac.equiv_double",
        "skill_slug": "frac.equivalent",
        "title": "Same amount, different pieces",
        "summary": "1/2 = 2/4 by splitting each half in two.",
        "problem": "Show that 1/2 is the same amount as 2/4.",
        "steps": [
            "Start with 1/2 of a bar.",
            "Split each half into 2 equal mini-pieces → the whole now has 4 equal pieces.",
            "The shaded half is now 2 of those 4 pieces → 2/4.",
            "Same shaded amount, different writing: 1/2 = 2/4.",
        ],
        "takeaway": "Multiply (or divide) top and bottom by the same number to make equivalents.",
        "counterexample": "Adding the same number to top and bottom does not keep the value.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Equivalent fractions", "Fraction sense"],
        "grade_min": 3,
        "grade_max": 6,
        "sort_order": 40,
    },
    {
        "slug": "we.frac.equiv_add_counter",
        "skill_slug": "frac.equivalent",
        "title": "Adding to both sides is not equivalence",
        "summary": "Counterexample: 1/2 is not 2/3.",
        "problem": "Someone says 1/2 = 2/3 because they added 1 to top and bottom. Is that right?",
        "steps": [
            "1/2 of a bar is half shaded.",
            "2/3 of a bar is more than half shaded.",
            "They are different amounts — adding to top and bottom is not a safe move.",
        ],
        "takeaway": "Only multiply or divide top and bottom by the same nonzero number.",
        "counterexample": "",
        "kind": "counterexample",
        "subject_name": "Math Foundations",
        "topic_names": ["Equivalent fractions"],
        "grade_min": 3,
        "grade_max": 6,
        "sort_order": 41,
    },
    {
        "slug": "we.frac.compare_same_den",
        "skill_slug": "frac.compare",
        "title": "Same-size pieces",
        "summary": "With the same denominator, larger numerator is larger.",
        "problem": "Which is larger, 2/5 or 4/5?",
        "steps": [
            "Both fractions have denominator 5 → pieces are the same size.",
            "2/5 means 2 pieces; 4/5 means 4 pieces.",
            "More same-size pieces → 4/5 is larger.",
        ],
        "takeaway": "Same denominator → compare numerators.",
        "counterexample": "With different denominators, bigger top is not always bigger overall.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Comparing fractions", "Fraction sense"],
        "grade_min": 3,
        "grade_max": 6,
        "sort_order": 50,
    },
    {
        "slug": "we.frac.compare_bigger_bottom_counter",
        "skill_slug": "frac.compare",
        "title": "Bigger bottom is not bigger amount",
        "summary": "Counterexample: 1/2 vs 1/8.",
        "problem": "Is 1/8 bigger than 1/2 because 8 is bigger than 2?",
        "steps": [
            "1/2 is one of two equal parts — half the whole.",
            "1/8 is one of eight equal parts — a much smaller bite.",
            "So 1/2 is larger, even though 8 > 2.",
        ],
        "takeaway": "For unit fractions, a larger denominator means smaller pieces.",
        "counterexample": "",
        "kind": "counterexample",
        "subject_name": "Math Foundations",
        "topic_names": ["Comparing fractions"],
        "grade_min": 3,
        "grade_max": 6,
        "sort_order": 51,
    },
    {
        "slug": "we.frac.add_like_pizza",
        "skill_slug": "frac.add_like",
        "title": "Adding same-size slices",
        "summary": "Keep the denominator; add the tops.",
        "problem": "What is 1/6 + 4/6?",
        "steps": [
            "Both pieces are sixths — same size.",
            "Add the numerators: 1 + 4 = 5.",
            "Keep the denominator 6 → 5/6.",
        ],
        "takeaway": "Like denominators: add tops, keep the bottom.",
        "counterexample": "Do not add denominators (1/6 + 4/6 is not 5/12).",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Adding fractions"],
        "grade_min": 3,
        "grade_max": 6,
        "sort_order": 60,
    },
    {
        "slug": "we.frac.add_like_den_counter",
        "skill_slug": "frac.add_like",
        "title": "Don't add the bottoms",
        "summary": "Counterexample for adding denominators.",
        "problem": "Is 1/4 + 2/4 = 3/8?",
        "steps": [
            "1/4 + 2/4 means three fourths of the same whole → 3/4.",
            "3/8 is a different amount (smaller pieces).",
            "Adding bottoms makes the pieces the wrong size.",
        ],
        "takeaway": "Only add numerators when denominators already match.",
        "counterexample": "",
        "kind": "counterexample",
        "subject_name": "Math Foundations",
        "topic_names": ["Adding fractions"],
        "grade_min": 3,
        "grade_max": 6,
        "sort_order": 61,
    },
    {
        "slug": "we.frac.add_unlike_thirds_sixths",
        "skill_slug": "frac.add_unlike",
        "title": "Common pieces first",
        "summary": "Rewrite with a common denominator, then add.",
        "problem": "What is 1/3 + 1/6?",
        "steps": [
            "Thirds and sixths are different sizes — make them match.",
            "1/3 = 2/6 (split each third in half).",
            "2/6 + 1/6 = 3/6, which is also 1/2.",
        ],
        "takeaway": "Unlike denominators: find equal-size pieces first, then add.",
        "counterexample": "Adding tops and bottoms separately (1/3 + 1/6 ≠ 2/9).",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Adding fractions"],
        "grade_min": 4,
        "grade_max": 7,
        "sort_order": 70,
    },
    {
        "slug": "we.alg.variable_bag",
        "skill_slug": "alg.variable_as_unknown",
        "title": "A mystery bag",
        "summary": "A letter stands for an unknown amount.",
        "problem": "A bag has some marbles. Call that number m. You add 3 marbles and now have 10. What does that mean?",
        "steps": [
            "m stands for how many were in the bag at the start.",
            "Adding 3 means m + 3.",
            "Together that equals 10: m + 3 = 10.",
        ],
        "takeaway": "A letter is a stand-in for a number we do not know yet.",
        "counterexample": "m is not a label for 'marbles word' — it is a number amount.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Variables & unknowns", "Simple equations"],
        "grade_min": 5,
        "grade_max": 8,
        "sort_order": 80,
    },
    {
        "slug": "we.alg.balance_scale",
        "skill_slug": "alg.balance_idea",
        "title": "Keep the scale even",
        "summary": "Whatever you do to one side, do to the other.",
        "problem": "A balance has a box and 2 cubes on the left, and 8 cubes on the right. It is balanced. What stays true if we remove 2 cubes from both sides?",
        "steps": [
            "Balanced means both sides have the same total weight.",
            "Remove 2 cubes from the left and 2 from the right.",
            "It is still balanced — now the box alone matches 6 cubes.",
        ],
        "takeaway": "Equality stays true when both sides get the same change.",
        "counterexample": "Removing cubes from only one side tips the balance.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Variables & unknowns", "Simple equations"],
        "grade_min": 5,
        "grade_max": 8,
        "sort_order": 90,
    },
    {
        "slug": "we.alg.balance_one_step",
        "skill_slug": "alg.one_step_equation",
        "title": "Balance scale +3",
        "summary": "Undo addition with subtraction on both sides.",
        "problem": "Solve x + 3 = 10.",
        "steps": [
            "Think of a balance: left side x + 3, right side 10.",
            "Subtract 3 from both sides to keep balance.",
            "x + 3 − 3 = 10 − 3 → x = 7.",
            "Check: 7 + 3 = 10 ✓",
        ],
        "takeaway": "Do the same undo-step on both sides.",
        "counterexample": "Only changing one side tips the balance.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Simple equations", "One-step equations"],
        "grade_min": 5,
        "grade_max": 8,
        "sort_order": 100,
    },
    {
        "slug": "we.alg.one_step_multiply",
        "skill_slug": "alg.one_step_equation",
        "title": "Undo multiply with divide",
        "summary": "3x = 12 → divide both sides by 3.",
        "problem": "Solve 3x = 12.",
        "steps": [
            "3x means 3 groups of x.",
            "Divide both sides by 3 to undo the multiply.",
            "x = 12 ÷ 3 = 4.",
            "Check: 3 × 4 = 12 ✓",
        ],
        "takeaway": "Multiplication and division undo each other on both sides.",
        "counterexample": "Subtracting 3 from both sides does not undo 'times 3'.",
        "kind": "example",
        "subject_name": "Math Foundations",
        "topic_names": ["Simple equations"],
        "grade_min": 5,
        "grade_max": 8,
        "sort_order": 101,
    },
]
