# Generated by Django 5.1.7 on 2026-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini / tutor chat"),
                            ("tts", "Text-to-speech"),
                            ("stt", "Speech-to-text"),
                            ("api", "Backend API"),
                            ("lesson", "Lesson UI"),
                            ("learning", "Learning events"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=240)),
                ("code", models.CharField(blank=True, default="", max_length=64)),
                ("component", models.CharField(blank=True, default="", max_length=80)),
                ("path", models.CharField(blank=True, default="", max_length=200)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("client_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, default="", max_length=40)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="core_client_kind_943d11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("value", models.FloatField(default=1.0)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("client_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "user_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "-created_at"],
                        name="core_produc_name_bb8e20_idx",
                    )
                ],
            },
        ),
    ]
