# Generated by Django 5.1.7 on 2026-08-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("category", models.CharField(db_index=True, max_length=40)),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("high", "High"), ("info", "Info")],
                        db_index=True,
                        default="high",
                        max_length=16,
                    ),
                ),
                ("age_band", models.CharField(blank=True, default="", max_length=20)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "component",
                    models.CharField(blank=True, default="lesson", max_length=80),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("client_ts", models.DateTimeField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="core_safety_severit_e41ff6_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="core_safety_categor_a623d1_idx",
                    ),
                ],
            },
        ),
    ]
