# Generated by Django 5.1.7 on 2026-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_safetyevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        default="manual",
                        help_text="manual | schedule | api",
                        max_length=40,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "-started_at"],
                        name="core_jobrun_name_64e01e_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_jobrun_status_9edfab_idx",
                    ),
                ],
            },
        ),
    ]
